import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'demo1';
  keyword = '';
  data: any;
  sitename = '123';

  constructor(private http: HttpClient) {
  }

  ngOnInit(): void {
    this.http.get('/api/articles.json')
      .subscribe(
        (value) => {
          this.data = value;
        }
      );
  }

  headerClickLogo(str: string) {
    this.keyword = str;
  }
}
// Generated by https://quicktype.io

export interface Article {
  id: number;
  href: string;
  title: string;
  date: string;
  author: string;
  category: string;
  'category-link': string;
  summary: string;
}

